# Generated by Django 5.1 on 2024-08-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_book_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
