# Generated by Django 5.1 on 2024-08-24 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_book_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Chapter_number', models.IntegerField()),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='coding_images/')),
                ('code', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_next_page', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='blog.book')),
            ],
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
