# Generated by Django 5.1 on 2024-08-24 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_chapter_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='Chapter_number',
            new_name='chapter_number',
        ),
    ]
