# Generated by Django 5.1 on 2024-08-24 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_chapter_number_chapter_chapter_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Article',
        ),
    ]
