# Generated by Django 5.1 on 2024-08-24 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_rename_chapter_number_chapter_page_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='page_number',
            new_name='chapter_number',
        ),
    ]
