# Generated by Django 5.1 on 2024-08-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_rename_page_number_chapter_chapter_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='book',
            new_name='article',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
