# Generated by Django 5.1 on 2024-08-24 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_rename_book_chapter_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='blog.article'),
        ),
    ]
